# Generated by Django 5.1.3 on 2024-11-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='url_temario',
            field=models.URLField(blank=True, null=True),
        ),
    ]
