# Generated by Django 5.1.3 on 2024-11-17 04:16

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inscripcioncurso_comprobante_anticipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='url_temario',
        ),
        migrations.AddField(
            model_name='curso',
            name='temario_pdf',
            field=models.FileField(blank=True, help_text='Sube el temario del curso en formato PDF', null=True, upload_to=core.models.temario_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
