# Generated by Django 5.1.3 on 2024-11-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_curso_url_temario_curso_temario_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='user',
            name='apellidoPaterno',
        ),
        migrations.AddField(
            model_name='user',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='apellido materno'),
        ),
        migrations.AddField(
            model_name='user',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
